In [6]:
import helpers
import importlib

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
case_df = pd.read_excel("cases.xlsx")
case_df.head()

,case,solution_method,time_scheme,conv_scheme,RE,N,DX,DT_MAX,DT,CFL,URFP,URFU,diverging_factor,IT,clock_time,colour,compare_diff,plot,Coldumn3,Time (min)
0,1.0,EFSM,1,UDS,1000,16,0.062500,0.062500,0.1500,2.400,NaN,-1.0,0.2000,260.0,0.247447,C0,16.666667,25.0,10.4000,0.004124
1,2.0,EFSM,1,UDS,1000,32,0.031250,0.031250,0.0500,1.600,NaN,-1.0,0.1000,860.0,3.887910,C0,50.000000,100.0,8.6000,0.064799
2,3.0,EFSM,1,UDS,1000,64,0.015625,0.015625,0.0150,0.960,NaN,-1.0,0.0200,3322.0,44.980831,C0,166.666667,250.0,13.2880,0.749681
3,4.0,EFSM,1,UDS,1000,128,0.007812,0.007812,0.0050,0.640,NaN,-1.0,0.0100,11952.0,377.196014,C0,500.000000,1000.0,11.9520,6.286600
4,5.0,EFSM,1,UDS,1000,256,0.003906,0.003906,0.0015,0.384,NaN,-1.0,0.0025,43836.0,3393.875980,C1,1666.666667,5000.0,8.7672,56.564600

In [ ]:
importlib.reload(helpers)
CavityCase = helpers.CavityCase
CaseManager = helpers.CaseManager

groups = {
    "Explicit Euler QUICK": CaseManager([16,17,18,19,20], solution_method="EFSM", time_scheme=1, N=64, conv_scheme="quick", RE=1000),
    "Explicit Euler UDS": CaseManager([31,34,33,32, 35, 36,37], solution_method="EFSM", time_scheme=1, N=64, conv_scheme="uds", RE=1000),
    # "AB2": CaseManager([21,22,23,24,25], solution_method="EFSM", time_scheme=2, N=64, conv_scheme="quick", RE=1000),
    "SIMPLE": CaseManager([28], solution_method="simple", N=64, conv_scheme="uds", RE=1000)
}

In [ ]:
# groups["EFSM Explicit Euler"].compare_meta()
groups["Explicit Euler QUICK"].compare_meta().sort_values(by='DT').reset_index()

,index,solution_method,conv_scheme,RE,N,time_scheme,DT,clock_time,IT,sum_N,total_outer_iterations,total_inner_iterations,avg_inner_per_outer
0,20,fs,quick,1000.0,64,1,0.0005,76.141212,63517,3617,63517,72340,1.138908
1,19,fs,quick,1000.0,64,1,0.0010,47.817623,35260,2668,35260,53360,1.513330
2,18,fs,quick,1000.0,64,1,0.0050,34.663536,9328,6445,9328,128900,13.818611
3,17,fs,quick,1000.0,64,1,0.0100,48.560310,5552,10979,5552,219580,39.549712
4,16,fs,quick,1000.0,64,1,0.0150,61.849926,4202,14547,4202,290940,69.238458

In [96]:
groups["AB2"].compare_meta().sort_values(by='DT').reset_index()[['DT', 'IT']]-groups["Explicit Euler QUICK"].compare_meta().sort_values(by='DT').reset_index()[['DT', 'IT']]

    DT  IT
0  0.0 -17
1  0.0   2
2  0.0  11
3  0.0  -1
4  0.0 -12